ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-8.14.7}

# Elasticsearch 플러그인 설정을 여기에 추가하세요
# 예시: RUN elasticsearch-plugin install analysis-icu
