name: CouponPop CI Build & Test

on:
  workflow_call:
    inputs:
      branch_name:
        description: 'The name of the branch (e.g., dev, main)'
        required: true
        type: string
    outputs:
      image_uri:
        description: "Built Docker image URI (only for 'main' branch)"
        value: ${{ jobs.build-and-package.outputs.image_uri }}
    secrets:
      AWS_REGION:
        required: true
      AWS_IAM_ROLE_ARN:
        required: true
      ECR_REPOSITORY:
        required: true
      FCM_SERVICE_ACCOUNT_KEY_JSON:
        required: true
      SSM_PARAMETER_NAME:
        required: true


jobs:
  build-and-package:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      image_uri: ${{ steps.build-image.outputs.image_uri }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Create secrets for Test
        run: |
          mkdir -p src/main/resources/firebase
          echo "${{ secrets.FCM_KEY_JSON_B64 }}" | base64 --decode > src/main/resources/firebase/serviceAccountKey.json

      - name: Verify key file content
        run: |
          echo "Verifying file content (first 50 characters):"
          head -c 50 src/main/resources/firebase/serviceAccountKey.json

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle and Run Tests
        env:
          SPRING_PROFILES_ACTIVE: test
        run: ./gradlew clean build

      - name: Remove secrets
        run: rm rf src/main/resources/firebase

      # ================================================================
      #  main 브랜치일 경우에만 실행
      # ================================================================

      - name: Configure AWS credentials (if main)
        #if: inputs.branch_name == 'main'
        if: inputs.branch_name == 'chore/cicd-v1'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR (if main)
        #if: inputs.branch_name == 'main'
        if: inputs.branch_name == 'chore/cicd-v1'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image (if main)
        #if: inputs.branch_name == 'main'
        if: inputs.branch_name == 'chore/cicd-v1'
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          IMAGE_URI="$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
          echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT

      - name: Update SSM Parameter Store with new image URI
        #if: inputs.branch_name == 'main'
        if: inputs.branch_name == 'chore/cicd-v1'
        run: |
          aws ssm put-parameter \
            --name "${{ secrets.SSM_PARAMETER_NAME }}" \
            --value "${{ steps.build-image.outputs.image_uri }}" \
            --type "String" \
            --overwrite
