name: CouponPop Main CI/CD

on:
  push:
    branches:
      - chore/cicd-jacoco
      - dev
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
      - '.github/ISSUE_TEMPLATE/**'
      - 'LICENSE'
  pull_request:
    branches:
      - dev
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
      - '.github/ISSUE_TEMPLATE/**'
      - 'LICENSE'

jobs:
  # =================================================================
  # Job 1: Call Reusable CI Pipeline (dev, main 공통 실행)
  # dev, main에서 모두 실행됩니다. 브랜치에 따라 내부 동작이 달라집니다.
  # =================================================================
  call-ci:
    name: CI - Build, Test & Package
    uses: ./.github/workflows/v1-ci-pipeline.yml
    permissions:
      id-token: write
      contents: read
    with:
      # 현재 브랜치 이름('dev' 또는 'main')을 전달
      #branch_name: ${{ github.ref_name }}
      branch_name: main
    secrets: inherit

  # =================================================================
  # Job 2: Call Reusable CD Pipeline (main 브랜치 전용 실행)
  # =================================================================
  call-cd:
    name: CD - Deploy to Production
    if: github.ref_name == 'main' && github.event_name == 'push' && needs.call-ci.result == 'success'
    needs: call-ci
    uses: ./.github/workflows/v1-cd-blue-green.yml
    permissions:
      id-token: write
      contents: read
    with:
      image_uri: ${{ needs.call-ci.outputs.image_uri }}
    secrets: inherit